---
         gitlab-runner \
         register -n \
         --name "Docker Runner" \
         --executor docker \
         --docker-image docker:latest \
         --docker-volumes /var/run/docker.sock:/var/run/docker.sock \
         --url http://172.16.226.10 \
         --registration-token diGyT9fbFfF1T2cgxkeZ \
         --tag-list prod

- name: cluster | ManagerGitlab | Dockerfile create 
  shell: >
          echo "
          FROM ubuntu:14.04

          ADD https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 /usr/bin/dumb-init
          RUN chmod +x /usr/bin/dumb-init

          RUN apt-get update -y && \
              apt-get upgrade -y && \
              apt-get install -y ca-certificates wget apt-transport-https vim nano && \
              apt-get clean && \
              rm -rf /var/lib/apt/lists/*

          RUN echo "deb https://packages.gitlab.com/runner/gitlab-ci-multi-runner/ubuntu/ `lsb_release -cs` main" > /etc/apt/sources.list.d/runner_gitlab-ci-multi-runner.list && \
              wget -q -O - https://packages.gitlab.com/gpg.key | apt-key add - && \
              apt-get update -y && \
              apt-get install -y gitlab-ci-multi-runner && \
              wget -q https://github.com/docker/machine/releases/download/v0.7.0/docker-machine-Linux-x86_64 -O /usr/bin/docker-machine && \
              chmod +x /usr/bin/docker-machine && \
              apt-get clean && \
              mkdir -p /etc/gitlab-runner/certs && \
              chmod -R 700 /etc/gitlab-runner && \
              rm -rf /var/lib/apt/lists/*

          ADD entrypoint /
          RUN chmod +x /entrypoint

          VOLUME ["/etc/gitlab-runner", "/home/gitlab-runner"]
          ENTRYPOINT ["/usr/bin/dumb-init", "/entrypoint"]
          CMD ["run", "--user=gitlab-runner", "--working-directory=/home/gitlab-runner"]

          RUN gitlab-runner \
              register -n \
              --name "Docker Runner" \
              --executor docker \
              --docker-image docker:latest \
              --docker-volumes /var/run/docker.sock:/var/run/docker.sock \
              --url http://"{{ gitlab_url }}" \
              --registration-token "{{ feed_token }}" \
              --tag-list toto
          " >> fileName
#                                   echo "127.0.0.1   registry.me" | sudo tee -a /etc/hosts
  become: true
  delegate_to: "{{ docker_swarm_addr }}"
  ignore_errors: true


- name: Download gitlab-runner binary
  get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    dest: /usr/bin/gitlab-runner
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root

- name: Create group
  group:
    name: gitlab-runner

- name: Create user
  user:
    name: gitlab-runner
    create_home: yes
    groups:
      - gitlab-runner
      - docker

- name: Install gitlab-runner
  shell: "gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner"
  ignore_errors: true

- name: start gitlab-runner
  shell: "gitlab-runner start"

- name: copy register script
  copy:
    src: register.sh
    dest: /usr/bin/register
    mode: u=rwx,g=rx,o=rx

- name: register runner
  shell: "register '{{runner_token}}' '{{runner_gitlab_url}}' '{{ runner_name }}'"

- name: set concurrent jobs
  shell: sed -i -e 's/concurrent = [0-9]/concurrent = {{runner_concurrent}}/g' /etc/gitlab-runner/config.toml

- name: start gitlab-runner
  shell: "gitlab-runner start"





  
- name: cluster | ManagerGitlab | Dockerfile create 
  shell: >
          echo "
          FROM ubuntu:14.04

          ADD https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 /usr/bin/dumb-init
          RUN chmod +x /usr/bin/dumb-init

          RUN apt-get update -y && \
              apt-get upgrade -y && \
              apt-get install -y ca-certificates wget apt-transport-https vim nano && \
              apt-get clean && \
              rm -rf /var/lib/apt/lists/*

          RUN echo "deb https://packages.gitlab.com/runner/gitlab-ci-multi-runner/ubuntu/ `lsb_release -cs` main" > /etc/apt/sources.list.d/runner_gitlab-ci-multi-runner.list && \
              wget -q -O - https://packages.gitlab.com/gpg.key | apt-key add - && \
              apt-get update -y && \
              apt-get install -y gitlab-ci-multi-runner && \
              wget -q https://github.com/docker/machine/releases/download/v0.7.0/docker-machine-Linux-x86_64 -O /usr/bin/docker-machine && \
              chmod +x /usr/bin/docker-machine && \
              apt-get clean && \
              mkdir -p /etc/gitlab-runner/certs && \
              chmod -R 700 /etc/gitlab-runner && \
              rm -rf /var/lib/apt/lists/*

          ADD entrypoint /
          RUN chmod +x /entrypoint

          VOLUME ["/etc/gitlab-runner", "/home/gitlab-runner"]
          ENTRYPOINT ["/usr/bin/dumb-init", "/entrypoint"]
          CMD ["run", "--user=gitlab-runner", "--working-directory=/home/gitlab-runner"]

          RUN gitlab-runner \
              register -n \
              --name "Docker Runner" \
              --executor docker \
              --docker-image docker:latest \
              --docker-volumes /var/run/docker.sock:/var/run/docker.sock \
              --url http://"{{ gitlab_url }}" \
              --registration-token "{{ feed_token }}" \
              --tag-list toto
          " >> Dockerfile
