---

########
#####initialisation du manager 
########


- name: cluster | manager |Initialize Docker Swarm
  shell: >
        docker swarm init
  run_once: true
  ignore_errors: true
  tags: swarm


- name: cluster | manager | Check if Swarm is Already
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm


########
#####Set de l'inventory_hostname 
########


###CaptureTheToken for join worker to manager
- name: cluster | manager | Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: docker_swarm_token
  tags: swarm


###catch token
- name: cluster | manager | Swarm-token-catch
  set_fact:
    docker_swarm_manager_token: "{{ docker_swarm_token.stdout }}"



###define addr manager

- name: cluster | manager | Defining Docker Swarm Manager Address
  set_fact:
    docker_swarm_manager_address: "{{ docker_swarm_addr }}"



- name: cluster | worker | Joining Docker Swarm Workers To Cluster
  command: >
         docker swarm join 
         --token "{{ docker_swarm_token.stdout }}" \
         "{{ docker_swarm_addr }}:{{ docker_swarm_port }}"
  become: true
  delegate_to: "{{ addr_worker_1 }}"
  ignore_errors: true

  

- name: cluster | worker | Joining Docker Swarm Workers To Cluster
  command: >
         docker swarm join 
         --token "{{ docker_swarm_token.stdout }}" \
         "{{ docker_swarm_addr }}:{{ docker_swarm_port }}"
  become: true
  delegate_to: "{{ addr_worker_2 }}"
  ignore_errors: true

  



